# 389. Find the Difference   QuestionEditorial Solution  My Submissions
# Total Accepted: 34621
# Total Submissions: 69474
# Difficulty: Easy
# Contributors: Admin
# Given two strings s and t which consist of only lowercase letters.
# 
# String t is generated by random shuffling string s and then add one more letter at a random position.
# 
# Find the letter that was added in t.
# 
# Example:
# 
# Input:
# s = "abcd"
# t = "abcde"
# 
# Output:
# e
# 
# Explanation:
# 'e' is the letter that was added.
# Subscribe to see which companies asked this question
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        dic = {}
        for char in s:
            if char not in dic:
                dic[char] = 1
            else:
                dic[char] += 1
        
        for char in t:
            if char not in dic:
                return char
            if char in dic and dic[char] <= 0:
                return char
            dic[char] -= 1
